import { Anton, Open_Sans } from "next/font/google";

import Headers from "./components/Headers";
import Footer from "./components/Footer";
import "./globals.css";

const anton = Anton({
  weight: '400',
  variable: "--font-anton",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-openSans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${anton.variable} ${openSans.variable} antialiased flex flex-col items-center min-h-screen`}
      >
        <header className="w-full h-[48px] bg-[#191970] flex justify-center items-center p-7">
          <Headers/>
        </header>

        <main className="flex-grow">
          {children}
        </main>

        <footer className="w-full h-[156px] bg-[#191970]">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}